### ISSUE TITLE
Architectural Design

### ISSUE THREAD

**Issue by ahmedazz260** [MUHC-DP-Project/pbrn-gateway#9]
# Goal
Your task is to design the architecture of the system and document it.
The design will cover the points below.
## Choice of the technology and their versions
* Programming Languages
* Database Solution
* API
* Unit test FrameWork
* Continuous integration server
* Source control system
* 3rd party software  && be careful about open source projects!!!

## Target Platform
* HW && SW, such as OS, servers and Licensing 
* Mecanism for authentication : MUHC ==> https://muhc.ca/user/login
* Data encryption if needed
* Protocols
* !! Privacy and security imposed by MUHC

## Define Layers &&  subsytems
* Diagrams
* Documentation

PS: if you are already sure of your design and did not complete the documentation; you can let me know and I will assign some tasks to the devs.

**Comment by preyansh98** [comment]
![68747470733a2f2f692e696d6775722e636f6d2f76496e7870314d2e706e67](https://user-images.githubusercontent.com/1579701/100498449-99186180-3162-11eb-8333-da07b5d344aa.png)
